services:
  mongodb:
    image: mongo:7.0
    container_name: mesrakel-mongo-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=logistics_dev
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
