spring.application.name=mesrakel-logistics
spring.profiles.active=dev

# Production/Default Database Configuration
spring.mongodb.uri=mongodb://mongo.samuel.et/yesera
spring.mongodb.username=samuel
spring.mongodb.password=Sam@258741
spring.mongodb.ssl.enabled=true
spring.mongodb.representation.uuid=standard