# Override the default URI and point to the local Docker Compose MongoDB
spring.mongodb.uri=mongodb://admin:password@localhost:27017/logistics_dev?authSource=admin
spring.mongodb.ssl.enabled=false
spring.data.mongodb.uuid-representation=standard
